
<div class="card calendar-card">
    <div class="calendar-header">
        <strong id="calendarMonthYear">May 2023</strong>
        <div class="calendar-nav">
            <button id="prevMonthBtn"><i class='bx bx-chevron-left'></i></button>
            <button id="nextMonthBtn"><i class='bx bx-chevron-right'></i></button>
        </div>
    </div>
    
    <div class="calendar-grid">
        <span class="day-name">Mo</span>
        <span class="day-name">Tu</span>
        <span class="day-name">We</span>
        <span class="day-name">Th</span>
        <span class="day-name">Fr</span>
        <span class="day-name">Sa</span>
        <span class="day-name">Su</span>
    </div>
    
    <div class="calendar-days-grid" id="calendarDaysContainer">
        <!-- Calendar days will be generated by JS -->
    </div>

    <!-- Event Details -->
    <div class="calendar-event-details" id="calendarEventDetails">
        <!-- Events will be shown here when date is clicked -->
    </div>
</div>

<!-- Modal Select Month -->
<div class="calendar-modal" id="monthSelectModal" style="display: none;">
    <div class="calendar-modal-content">
        <div class="calendar-modal-header">
            <h3>Select Month</h3>
            <button class="calendar-modal-close" id="closeMonthModal">&times;</button>
        </div>
        <div class="calendar-modal-body">
            <div class="month-grid">
                <button class="month-btn" data-month="0">January</button>
                <button class="month-btn" data-month="1">February</button>
                <button class="month-btn" data-month="2">March</button>
                <button class="month-btn" data-month="3">April</button>
                <button class="month-btn" data-month="4">May</button>
                <button class="month-btn" data-month="5">June</button>
                <button class="month-btn" data-month="6">July</button>
                <button class="month-btn" data-month="7">August</button>
                <button class="month-btn" data-month="8">September</button>
                <button class="month-btn" data-month="9">October</button>
                <button class="month-btn" data-month="10">November</button>
                <button class="month-btn" data-month="11">December</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal Select Year -->
<div class="calendar-modal" id="yearSelectModal" style="display: none;">
    <div class="calendar-modal-content">
        <div class="calendar-modal-header">
            <h3>Select Year</h3>
            <button class="calendar-modal-close" id="closeYearModal">&times;</button>
        </div>
        <div class="calendar-modal-body">
            <div class="year-grid" id="yearGridContainer">
                <!-- Years will be generated by JS -->
            </div>
        </div>
    </div>
</div>